### ISSUE TITLE
Time-Parsing in vcard/vcal

### ISSUE THREAD

**Issue by andi-at** [pmengal/MailSystem.NET#10]
Keep getting erros parsing some time values - seems that there are some different time formats.
Praser.cs ParseDate():
I´ve added a else if for length=15, fixing my problem:

else if (input.Length == 15)
				{
					input = input.Insert(4, "-");
					input = input.Insert(7, "-");
					input = input.Insert(13, ":");
					input = input.Insert(16, ":");
				}

**Comment by reinaldocoelho** [comment]
@andi-at  I write a bug fix to this based on your sugestion.

I will close the issue, please, validate result after build.

Thanks.
