### ISSUE TITLE
Unable to download embeddedObjects from an email message.

### ISSUE THREAD

**Issue by maddisn** [pmengal/MailSystem.NET#14]
//I need to be able to download the embedded images from the mail messages`

            public void downlodInlineAttachments()
           {
            Imap4Client imap = new Imap4Client();
            List<Message> unreadAttachments = new List<Message>();
            
            //Authentication
            imap.ConnectSsl(Credential.outlookImapHost, Credential.outlookImapPort);
            imap.Login(Credential.outlookUserName, Credential.outlookPassword);

            Mailbox inbox = imap.SelectMailbox("inbox");
            int[] unread = inbox.Search("unseen");
            Console.WriteLine("Unread Messgaes: " + unread.Length);

            if (unread.Length > 0)
            {
                //fetch each unread message and insert into the Message List
                for (int i = 0; i < unread.Length; i++)
                {
                    Message unreadMessage = inbox.Fetch.MessageObject(unread[i]);
                    Message m = inbox.Fetch.MessageObject(unread[i]);
                    unreadAttachments.Add(unreadMessage);
                }

                //Iterate through a list of Messages and download the embedded objects locally
                //Can help with the syntax? It gives error
                foreach (MimePart embedded in _message.EmbeddedObjects)
                {
                    var filename = embedded.ContentName;
                    var binary = embedded.BinaryContent,
                    File.WriteAllBytes(filename, binary);
                }
            }
            else
            {
                Console.WriteLine("Unread Messages Not Found");
            }
         }

**Comment by reinaldocoelho** [comment]
@maddisn try that:

        public void downlodInlineAttachments()
       {
        Imap4Client imap = new Imap4Client();
        List<Message> unreadAttachments = new List<Message>();
        
        //Authentication
        imap.ConnectSsl(Credential.outlookImapHost, Credential.outlookImapPort);
        imap.Login(Credential.outlookUserName, Credential.outlookPassword);

        Mailbox inbox = imap.SelectMailbox("inbox");
        int[] unread = inbox.Search("unseen");
        Console.WriteLine("Unread Messgaes: " + unread.Length);

        if (unread.Length > 0)
        {
            //fetch each unread message and insert into the Message List
            for (int i = 0; i < unread.Length; i++)
            {
                Message unreadMessage = inbox.Fetch.MessageObject(unread[i]);
                foreach (MimePart embedded in unreadMessage.EmbeddedObjects)
                {
                    var filename = embedded.ContentName;
                    var binary = embedded.BinaryContent,
                    File.WriteAllBytes(filename, binary);
                }
            }
        }
        else
        {
            Console.WriteLine("Unread Messages Not Found");
        }
     }
