### ISSUE TITLE
Unable to login to gmail, "Web login required"

### ISSUE THREAD

**Issue by sixfootfour** [pmengal/MailSystem.NET#17]
Is there a workaround for logging into Gmail with the Imap4Client when you encounter a "weblogin required" error?

I have already enabled "Allow unsecure apps" for the Gmail account in question, and that got it working on my local machine - but after deploying the code to a server, I get the error again - and this time, I can't seem to get it working again. I tried visiting the url provided by google, as I thought that might be some sort of authentication method. I log in using my password, and all seems OK - but connecting with the Imap4Client still fails.

Below is the stacktrace and msgs for 
```

Unhandled Exception: ActiveUp.Net.Mail.Imap4Exception: Command "login myemail@gmail.com mypassword" failed : * NO [WEBALERT https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbttoGtD4OMtfxi7uAy8s84fzfawSNIPPED] Web login required.
170226012817375 NO [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)

    at ActiveUp.Net.Mail.Imap4Client.Command(String command, String stamp, CommandOptions options)
    at ActiveUp.Net.Mail.Imap4Client.Command(String command, CommandOptions options)
    at ActiveUp.Net.Mail.Imap4Client.Login(String username, String password)
```

**Comment by sixfootfour** [comment]
As it is not really an issue with Mailsystem.NET but rather with Gmail, I will close the incident.

For anybody that might stuble across this in the future, the thing to do is to enable two-factor auth on the account and generate an app password. That does the trick. That solution might not be for everybody, but hey... :)

**Comment by reinaldocoelho** [comment]
Thanks for reply @sixfootfour
