### ISSUE TITLE
Stackoverflowexception

### ISSUE THREAD

**Issue by Daniellait** [pmengal/MailSystem.NET#21]
While trying to fetch mails from an inbox, I got a stackoverflowexception.
By using memorydump and dotpeek on your dlls, I found the following:
public static Address ParseAddress(string input)
    {
      Address address = new Address();
      input = input.TrimEnd(';');
      try
      {
        if (input.IndexOf("<") == -1)
        {
          address.Email = Parser.RemoveWhiteSpaces(input);
        }
        else
        {
          if (input.IndexOf("\"") >= 0)
          {
            string oldValue = Regex.Match(input, "\".*\"").Value;
            address.Email = input.Replace(oldValue, "").Trim().TrimStart('<').TrimEnd('>');
            address.Name = oldValue;
            if (address.Email == "" && address.Name != "")
            {
              address.Email = address.Name;
              address.Name = "";
            }
          }
          else
          {
            address.Email = Regex.Match(input, "<(.|[.])*>").Value.TrimStart('<').TrimEnd('>');
            address.Name = input.Replace("<" + address.Email + ">", "");
          }
          address.Email = Parser.Clean(Parser.RemoveWhiteSpaces(address.Email)).Replace("\"", "");
          if (address.Name.IndexOf("\"") == -1)
            address.Name = Parser.Clean(address.Name);
          address.Name = address.Name.Trim(' ', '"');
        }
        return address;
      }
      catch
      {
        return new Address(input);
      }
    }

The input is the mail, which results in the error. The input is: "\" <Invoice@dymak.nl>". This looks wrong yes, but this is not the problem. 
The oldValue will now not have a length, and the try will fail. We therefor gets to catch, which calls the Address method again, with the same input. This will continue until stackoverflow has been reached. 
So can you fix this, so it doesn't run in circles indefinitely, but handles the error?

**Comment by reinaldocoelho** [comment]
Hi Daniel.

I solve the problem on the PullRequest #22.

Please check if the probem was solved on version 2.1.27 :-)

**Comment by Daniellait** [comment]
I was. Thank you
