### ISSUE TITLE
error parsing MS Exchange bodystructure response

### ISSUE THREAD

**Issue by rutonik** [pmengal/MailSystem.NET#23]
actual response from server
`* 3 FETCH (BODYSTRUCTURE (("text" "html" ("charset" "utf-8") NIL NIL "base64" 0 0 NIL NIL NIL NIL)("application" "octet-stream" ("name" "tmp_price.zip") NIL NIL "base64" 3281042 NIL ("attachment" ("filename" "tmp_price.zip")) NIL NIL) "mixed" ("boundary" "0a13d07f7e95b55bf35a04629d68ee9e") NIL NIL))
170404084703420 OK FETCH completed.
`

it crashes in BodyStructure
response doenst contain "bodystructure" (lowercase) and " UID"

**Comment by reinaldocoelho** [comment]
Hi @rutonik, can you give more information about how to reproduce problem?
The steps to reproduce for example or a EML file of email with error?

Thanks.

**Comment by rutonik** [comment]
https://pastebin.com/Lp7Ju62M
here is plain output for FETCH

the problem is only with latest MS Exchange
old version is working fine
this is happening with ANY letter

**Comment by reinaldocoelho** [comment]
Hi @rutonik.

I think that this doc explain this eml implementation: https://tools.ietf.org/html/rfc2184

I need to review the function Parser.ParseHeaderFields(), who has RegEx to recover name parts, but does not consider multiple parts.

**Comment by jstedfast** [comment]
You actually want the newer spec which is https://tools.ietf.org/html/rfc2231

@rutonik any chance you could test [MailKit](https://github.com/jstedfast/MailKit) for me to make sure it works with your server?

Thanks!

**Comment by reinaldocoelho** [comment]
Hi @rutonik !

Sorry for the long time to answer.
Finally we solve your bug and publish in version 2.1.34 (https://www.nuget.org/packages/MailSystem.Net-trunk/2.1.34)

Thank you for report this bug to us.
