### ISSUE TITLE
pop3 client - retrieve messages from a selected date.

### ISSUE THREAD

**Issue by tonydema** [pmengal/MailSystem.NET#25]
Hello.
I am using your library MailSystem.NET and i have a question.
Is there a way to retrieve messages from a selected date using a pop3 client?
I have seen examples with IMAP but i should use pop3.

Thanks

**Comment by reinaldocoelho** [comment]
Hello @tonydema.

At this time Lib does not support date filtering for POP3.
That I know, POP3 servers doesn´t accept the filter command to filter date.

Some servers accept specific commands to reduce download lenght, like gmail that has RECENT command, that gets only last 30 days emails.

**Comment by tonydema** [comment]
Ok Thanks for fast response!
