### ISSUE TITLE
POP3 Library error

### ISSUE THREAD

**Issue by kadeshar** [pmengal/MailSystem.NET#28]
Ok, now i know issue @reinaldocoelho 

Old library form May 2016:
https://drive.google.com/file/d/0B3wpZmFEwnZ_eEJEX3JOaV9GR1k/view?usp=sharing

Newest library:
https://drive.google.com/file/d/0B3wpZmFEwnZ_OUk2MDd4UUlZaU0/view?usp=sharing

Is new library count used space on e-mail account (variable TotalSize)? If yes then Int32 is to small for that.
Response from i think library (not server) is: 
Value was either too large or too small for an Int32

**Comment by reinaldocoelho** [comment]
@kadeshar Sorry for long time to answer.
Can you send to me the steps to reproduce this problem?
And yes, we work with Int32 in thos field.

Thanks.

**Comment by reinaldocoelho** [comment]
Closing for no return.
