### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.' in Message.cs when attempting to save email to HDD. 

### ISSUE THREAD

**Issue by SWvheerden** [pmengal/MailSystem.NET#31]
This piece of code (line 1067-1073) in Header.cs throws an System.NullReferenceException: 'Object reference not set to an instance of an object.'  exception

_UsenetXrefList xref = new UsenetXrefList();
                xref.Host = HeaderFields["xref"].Split(' ')[0];
                string[] splitted = HeaderFields["xref"].Split(' ');
                for (int i = 1; i < splitted.Length; i++)
                    if (splitted[i].IndexOf(":") != -1)
                        xref.Groups.Add(splitted[i].Split(':')[0], splitted[i].Split(':')[1]);
                return xref;_

This happens because the xref key does not exist.

Whats the purpose of the xref header? And why does it not exist?  
Context: I am downloading an email through imap from an hmail server.

**Comment by reinaldocoelho** [comment]
Hi @SWvheerden !

XRef is not an necessary header, we have unit tests on code parsing emails without this header and no problem.
Xref is explained in RFC2076(RFC: https://tools.ietf.org/html/rfc2076) and contain that description:
"Used in Usenet News to store information to avoid showing a reader the same article twice if it was sent to more than one newsgroup. Only for local usage within one Usenet News server, should not be sent between servers"

Received  you an e-mail without that?
If you having this problem, can you send to us some EML for reproduce and test this case?

Thank you.

**Comment by SWvheerden** [comment]
Hi, 
Thanks for coming back.  Unfortunately I cant share the emails as they contain attachments with confidential information. 

But I am having two problems:

- Some emails cant be downloaded (hmail server and ActiveUP imap client both report the connection as forcibly closed by remote host), I get this when I try to fetch an email. Connection works fine, as well as to retrieve the number of message in the inbox. 
- Emails that are downloaded cant be saved to file. The xref null is an attempt to find the problem. 

I encountered the first problem and in an attempt to solve the problem I upgraded the library from v2.1.23.0 to v2.1.32.0 (the version on nuget), thats when I encountered the second problem. 
The emails that are not downloadable, can be downloaded via thunderbird and then imported via the Parser.ParseMessageFromFile() function. 

I dont know what code changed between the two versions. But something is causes error 2 that was not present before. But I am yet to find out exactly what causes issue 1.

**Comment by SWvheerden** [comment]
I found out why its emails downloaded is giving an Object reference not set to an instance of an object exception. I was wrong it has nothing to do with the xref. I never though of checking the unit tests. 

In the file TraceInfo.cs: Line 95-114
There is a function: public override string ToString().
This function only checks if the string is Empty and not null, in my case For, Via And Id was null. 
I changed the function to as follows (made all empty checks to null or empty):
```
public override string ToString()
        {
            string source = string.Empty;
            if (!string.IsNullOrEmpty(From))
                source += " from " + From + "\r\n ";
            if (!string.IsNullOrEmpty(By))
                source += " by " + By + "\r\n ";
            if (!string.IsNullOrEmpty(With))
                source += " with " + With + "\r\n ";
            if (!string.IsNullOrEmpty(For))
                source += " for " + For + "\r\n ";
            if (!string.IsNullOrEmpty(Via))
                source += " via " + Via + "\r\n ";
            if (!string.IsNullOrEmpty(Id))
                source += " id " + Id + "\r\n ";

            if (string.IsNullOrEmpty(source))
                return "";
            return source.Remove(0,source.Length - 3) + ";" + Date.ToString("r");
        }
```
This fixes the problem and makes the files downloadable.

**Comment by reinaldocoelho** [comment]
Sorry for the long time to answer.
I include this update on code and will launch in the next version.

Thank you for your help :-)

**Comment by reinaldocoelho** [comment]
Published on version: MailSystem.Net-trunk  2.1.36
Thank you!
