### ISSUE TITLE
Connection with Office365

### ISSUE THREAD

**Issue by maudhof** [pmengal/MailSystem.NET#39]
Hi

I am having trouble connecting to Office 365 server with StartTls.

The connection if started with ConnectSsl causes a Handshake error:

> System.IO.IOException was unhandled by user code
> HResult=-2146232800
> Message=The handshake failed due to an unexpected packet format.
> Source=System
> 

If initiated with method SmtpClient.Connect, when calling method Authenticate causes this error:

> Command "auth login" failed : 504 5.7.4 Unrecognized authentication type [SC1P15201CA0044.LAMP152.PROD.OUTLOOK.COM]

I got the connection using the following test code:

```
        public string ConnectStartTls (string host, int port, string localDomain)
        {
            OnConnecting ();
            base.Connect (host, port);
            string response = ReadLine ();
            Helo (localDomain);
            Command ("STARTTLS", 220);
            _sslStream = new SslStream (Stream);
            _sslStream.AuthenticateAsClient (host);
            Ehlo (localDomain);
            OnConnected (new ConnectedEventArgs (response));
            return response;
        }
```
 
Is this a real problem or is there a way to make StartTls connections in Office365 server?

**Comment by reinaldocoelho** [comment]
Hi @maudhof .
I will look for this issue, if you have some new information feel free to include in comments :-)
Thanks for help.

**Comment by reinaldocoelho** [comment]
Hi @maudhof.
I think that this issue could be related to Server Certificate that would be invalid.
You can try to ignore server certificates with this:
```csharp

        public void access_invalid_certificate_on_smtp_server()
        {
            var _selectedMailBox = "INBOX";
            using (var _clientImap4 = new Imap4Client())
            {
               // This create always true certificate:
                var handShake = new SslHandShake(_imapServerAddress, System.Security.Authentication.SslProtocols.Default);
                handShake.ServerCertificateValidationCallback = delegate { return true; };

                _clientImap4.ConnectSsl(_imapServerAddress, _imapPort, handShake);
                _clientImap4.LoginFast(_imapLogin, _imapPassword);

                // To see the names os all MailBox and found  Trash
                _clientImap4.LoadMailboxes();

                _clientImap4.Disconnect();
            }
        }
```

Can you verify if work?
