### ISSUE TITLE
Port MailSystem.NET to DotNet Core

### ISSUE THREAD

**Issue by reinaldocoelho** [pmengal/MailSystem.NET#4]
Create port of MailSystem to use with DotNetCore FrameWork.

**Comment by darklx** [comment]
Geeat!

**Comment by reinaldocoelho** [comment]
I will cancel this Issue.

**Comment by darklx** [comment]
@reinaldocoelho Is you found many difficult for poring to .NET Core ? Such as many PCL Class and thirdparty library Lost in .NET Core, so wait for right time?

**Comment by reinaldocoelho** [comment]
In parts yes, inside the MailSystem.NET code, there are points that I do not believe will be possible to convert.

Because MailSystem has multiple components, perhaps to allow a migration to be legal would generate a new project and migrate into parts.

I closed this issue tb because the MailKit, Mimekit for email itself is already supporting DotNet Core.

What is the part that most interests you in DotNet Core?
We could generate a poll to see what matters to people.

**Comment by darklx** [comment]
Thank you,I'm not sure now.I'm just looking forward , and interested in port to .NET Core's skill.
I'm still using full .NET Framework with mono runtime to develop on Mac and deploy on Linux production.

**Comment by reinaldocoelho** [comment]
I´m using dotnet core and recommend.
:-)
