### ISSUE TITLE
OAuth - IMAP - Office365

### ISSUE THREAD

**Issue by AJCheeseman** [pmengal/MailSystem.NET#55]
With Microsoft's decision that all O365 lose Basic Authentication in October 2022, will there be an update to MailSystem.NET for OAuth2 connection?

If this is already done, I apologize as I was unable to find the options related to that.

**Comment by bn-obelu** [comment]
Same here, didn't find a way for this.

**Comment by Hivanoe** [comment]
Same here, but with pop3 ...

**Comment by pmengal** [comment]
Hello all, it's not supported in this project, unfortunately and nobody in the team is planning it. Sorry for that.
