### ISSUE TITLE
Exception parsing VCAL-TODO

### ISSUE THREAD

**Issue by andi-at** [pmengal/MailSystem.NET#8]
Hello, 
got this exception when trying to parse a vcal file which only contain a TODO:
System.ArgumentOutOfRangeException: 
   bei System.String.Substring(Int32 startIndex, Int32 length)
   bei ActiveUp.Net.Groupware.vCalendar.Parser.GetEvents(String data)

You are missing following line of code wich checks if a VEVENT is there, insert following at GetEvent (just like you have on the GETTODO() funktion

if (data.IndexOf("BEGIN:VEVENT") > -1)

thanks!

**Comment by reinaldocoelho** [comment]
Hi @andi-at .

Sorry for the delay to return.

I have not yet worked with the calendar code, but for the cases you are listing, I am generating a simple unit test and making a correction.

I'll check your other tickets, but I can not tell the current status of the calendar code.

If you want to continue reporting the problems, I thank you and I will try to correct the problems.

I hope I have helped.

Reinaldo.

**Comment by reinaldocoelho** [comment]
I make a pull-request then close this issue.

Thanks.
