### ISSUE TITLE
vTodo parsing is completely missing

### ISSUE THREAD

**Issue by andi-at** [pmengal/MailSystem.NET#9]
Parsing of vTodo´s is completely missing:
`vTodo todo = new vTodo();
			todo.Summary = data;
			return todo;`

You completely lack support of saving ToDo´s, I would recommend to deactivate the whole vCalendar class until it´s useable?

**Comment by reinaldocoelho** [comment]
@andi-at Can you send to me an example of code you want to work?

I will create a unit test with then and work to support your need.

Thanks.

**Comment by reinaldocoelho** [comment]
Closing for no response.
